version: '3'

services:
  lapimate:
    build: .
    container_name: lapimate-app
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
